version: "2"
services:
  event_srv:
    container_name: event_srv
    build: .
    command: event-srv
    environment:
      EVENT_SRV_PORT: 3000
      EVENT_SRV_DB: "http://@docker:9200"
      EVENT_SRV_BUS: "localhost:9093"

    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
      - kafka

  elasticsearch:
    container_name: dev_elasticsearch
    image: elasticsearch:1.4.2
    ports:
      - "9200:9200"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka:
    container_name: dev_kafka
    image: wurstmeister/kafka
    hostname: kafka
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "events:1:2:compact"
    ports:
      - "9093:9092"
    depends_on:
      - zookeeper

  zookeeper:
    container_name: dev_zookeeper
    image: oddpoet/zookeeper
    hostname: zookeeper
    command:
      - "2181"
    ports:
      - "2181:2181"
